vim.keymap.set('n', '<leader>n', ':Explore<CR>')
vim.keymap.set('n', '<Esc>', ':nohlsearch<CR>', { silent = true })
vim.keymap.set('n', 'd', '"_d')
vim.keymap.set('n', 'D', '"_D')
vim.keymap.set('n', 'c', '"_c')
vim.keymap.set('n', 'C', '"_C')
vim.keymap.set('n', '<C-s>', vim.lsp.buf.definition, { silent = true })
vim.keymap.set('n', '<C-a>', function()
  vim.diagnostic.jump({
    count = 1,
    on_jump = function()
      vim.diagnostic.open_float({ focus = false })
    end,
  })
end, { silent = true })
vim.keymap.set('n', '<C-p>', function()
  require('fzf').find_files()
end, { silent = true })
vim.keymap.set('n', '<C-n>', function()
  require('fzf').grep_project()
end, { silent = true })
vim.keymap.set('n', '<leader>h', function()
  vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled())
end)
