alias p='bun'
alias 4='dig -4 +short myip.opendns.com @resolver1.opendns.com'
alias v.='fd --type f --hidden --exclude .git | fzf | xargs nvim'
alias ds='podman system prune -a --volumes'
alias db='psql "$(grep -hm1 "^DATABASE_URL=" .env .dev.vars 2>/dev/null | sed "s/^DATABASE_URL=//;s/^[\"'\'']//;s/[\"'\'']$//")"'
alias .='cd ..'
alias ..='cd ../..'
alias ...='cd ../../..'
alias ....='cd ../../../..'
alias .....='cd ../../../../..'
alias l='ls -A --color=always'
alias d='cd "$HOME/Desktop"'
alias dw='cd "$HOME/Downloads"'
alias z='cd "$HOME/Documents/$(fd --type d --max-depth 1 --base-directory $HOME/Documents | fzf)"'
alias lk='HOMEBREW_NO_INSTALL_FROM_API=1 brew update && brew list --formula | xargs brew upgrade && brew list --cask | xargs brew upgrade'
alias kl='brew cleanup && brew cleanup --prune-prefix'
