alias 4='dig +short myip.opendns.com @resolver1.opendns.com'
alias v.='fd --type f --hidden --exclude .git | fzf | xargs nvim'
alias ds='podman system prune -a --volumes'
alias db='psql "$( (grep -E "^DATABASE_URL=" .env 2>/dev/null || grep -E "^DATABASE_URL=" .dev.vars 2>/dev/null) | sed -e "s/^DATABASE_URL=//")"'
alias .='cd ..'
alias ..='cd ../..'
alias ...='cd ../../..'
alias ....='cd ../../../..'
alias .....='cd ../../../../..'
alias l='ls -A --color=always'
alias d='cd "$HOME/Desktop"'
alias dw='cd "$HOME/Downloads"'
alias z='cd "$HOME/Documents/$(fd --type d --max-depth 1 --base-directory $HOME/Documents | fzf)"'
alias lk='brew update && brew list --formula | xargs brew upgrade && brew list --cask | xargs brew upgrade'
alias kl='brew cleanup && brew cleanup --prune-prefix'
